### ISSUE TITLE
500 error when using Cookie driver

### ISSUE THREAD

**Issue by barchard** [duncanmcclean/simple-commerce#365]
```
[2021-02-18 02:03:59] local.ERROR: Call to undefined method DoubleThreeDigital\SimpleCommerce\Orders\Order::make() {"exception":"[object] (Error(code: 0): Call to undefined method DoubleThreeDigital\\SimpleCommerce\\Orders\\Order::make() at vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261)
[stacktrace]
#0 vendor/doublethreedigital/simple-commerce/src/Orders/Cart/Drivers/CookieDriver.php(33): Illuminate\\Support\\Facades\\Facade::__callStatic('make', Array)
#1 vendor/doublethreedigital/simple-commerce/src/Orders/Cart/Drivers/CartDriver.php(38): DoubleThreeDigital\\SimpleCommerce\\Orders\\Cart\\Drivers\\CookieDriver->makeCart()
#2 vendor/doublethreedigital/simple-commerce/src/Http/Controllers/CartItemController.php(18): DoubleThreeDigital\\SimpleCommerce\\Http\\Controllers\\CartItemController->makeCart()
#3 vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): DoubleThreeDigital\\SimpleCommerce\\Http\\Controllers\\CartItemController->store(Object(DoubleThreeDigital\\SimpleCommerce\\Http\\Requests\\CartItem\\StoreRequest))
#4 vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('store', Array)
#5 vendor/laravel/framework/src/Illuminate/Routing/Route.php(239): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(DoubleThreeDigital\\SimpleCommerce\\Http\\Controllers\\CartItemController), 'store')
#6 vendor/laravel/framework/src/Illuminate/Routing/Route.php(196): Illuminate\\Routing\\Route->runController()
#7 vendor/laravel/framework/src/Illuminate/Routing/Router.php(685): Illuminate\\Routing\\Route->run()
#8 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#9 vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#10 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#11 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#12 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#13 vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#14 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#15 vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#16 vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(62): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#17 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#18 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#19 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(167): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#22 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#23 vendor/laravel/framework/src/Illuminate/Routing/Router.php(687): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#24 vendor/laravel/framework/src/Illuminate/Routing/Router.php(662): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#25 vendor/laravel/framework/src/Illuminate/Routing/Router.php(628): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#26 vendor/laravel/framework/src/Illuminate/Routing/Router.php(617): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#27 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(165): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
```

A quick description of the issue you're facing.

Can't add items to cart when using CookieDriver

## How to reproduce

Try to use cookie driver. Attempt to save via AJAX

## What I expected

Items added to cart

## Environment

Copy the output of `php please support:details` into here.

```
php please support:details
Statamic 3.0.44 Pro
Laravel 7.30.4
PHP 7.4.14
aryehraber/statamic-captcha 1.3.0
doublethreedigital/sc-digital-products 2.0.2
doublethreedigital/simple-commerce 2.2.8
statamic/seo-pro 2.1.1
```

**Comment by duncanmcclean** [comment]
Fixed in [v2.2.9](https://github.com/doublethreedigital/simple-commerce/releases/tag/v2.2.9)
